name: Greeting
on: [push,workflow_dispatch]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: "Greet user"
              run: |
                 echo "hello world !"
                 git clone https://github.com/${{ github.repository }}.git